import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterLuxon } from '@mui/x-date-pickers/AdapterLuxon';
import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';
import { TextField, Snackbar, Button, Select, MenuItem, FormControl, InputLabel } from '@mui/material';
import { Alert } from '@mui/material';
import jsPDF from 'jspdf';
import 'jspdf-autotable'; // Import the plugin here
import SideNav from '../Components/sidenav/SideNav';

const CreateReport = () => {
    const [reportType, setReportType] = useState('day');
    const [specificTicket, setSpecificTicket] = useState('');
    const [status, setStatus] = useState('');
    const [startDate, setStartDate] = useState(null);
    const [endDate, setEndDate] = useState(null);
    const [userId, setUserId] = useState('');
    const [department, setDepartment] = useState('');
    const [building, setBuilding] = useState('');
    const [campus, setCampus] = useState('');
    const [jobOrders, setJobOrders] = useState([]);  // State for job orders
    const [noResults, setNoResults] = useState(false);

    // Fetch job orders dynamically
    useEffect(() => {
        const fetchJobOrders = async () => {
            try {
                const response = await axios.get('/api/jobOrders', { params: { status: 'approved' }, withCredentials: true });
                setJobOrders(response.data.requests);  // Assuming response contains job orders in `requests`
            } catch (error) {
                console.error('Error fetching job orders:', error);
            }
        };

        fetchJobOrders();
    }, []);

    const handleGenerateReport = async () => {
        try {
            const dateRange = startDate && endDate
                ? `${startDate.toISODate()}:${endDate.toISODate()}`
                : '';
    
            const response = await axios.get('/api/report', {
                params: { reportType, specificTicket, status, dateRange, userId, department, building, campus }
            });
            const requests = response.data.requests;
    
            if (requests.length === 0) {
                setNoResults(true);
                return;
            }
    
            const doc = new jsPDF();
            const logo = await import(/* webpackIgnore: true */ '../assets/img/nu_logo.png'); // Update the path to your logo
    
            // Add logo
            doc.addImage(logo.default, 'PNG', 10, 10, 50, 20); // Adjust the position and size as needed
    
            // Report Title
            doc.setFontSize(24);
            doc.setFont('Helvetica', 'bold');
            doc.text('Job Order Report', 70, 30);
    
            // User Information
            doc.setFontSize(12);
            doc.setFont('Helvetica', 'normal');
            doc.text(`Generated by: ${getLoggedInUserName()}`, 10, 50); // Replace with a function to get the logged-in user's name
            doc.text(`Generated on: ${new Date().toLocaleString()}`, 10, 60);
            
            doc.text(`Report Type: ${reportType}`, 10, 70);
            doc.text(`Status: ${status || 'All'}`, 10, 80);
            doc.text(`Date Range: ${dateRange || 'N/A'}`, 10, 90);
            doc.text(`User ID: ${userId || 'N/A'}`, 10, 100);
            doc.text(`Department: ${department || 'N/A'}`, 10, 110);
            doc.text(`Building: ${building || 'N/A'}`, 10, 120);
            doc.text(`Campus: ${campus || 'N/A'}`, 10, 130);
    
            // Table header
            doc.autoTable({
                startY: 140,
                head: [['ID', 'Name', 'Status', 'Date']],
                body: requests.map(req => [
                    req._id,
                    `${req.firstName} ${req.lastName}`,
                    req.status,
                    new Date(req.createdAt).toLocaleDateString()
                ]),
                theme: 'grid', // You can change the table theme here
            });
    
            // Add signature section
            const signatureY = doc.autoTable.previous.finalY + 20;
            doc.text('________________________', 180, signatureY, { align: 'right' });
            doc.text('Signature', 180, signatureY + 10, { align: 'right' });
    
            // Additional placeholders for signatures
            doc.text('________________________', 30, signatureY, { align: 'left' });
            doc.text('Authorized Signature', 30, signatureY + 10, { align: 'left' });
    
            doc.save('Job_Order_Report.pdf');
        } catch (error) {
            console.error('Error generating report:', error);
        }
    };
    
    // Function to get the logged-in user's name from cookies or other storage
    const getLoggedInUserName = () => {
        // Assume you have stored the user's name in cookies
        const userData = JSON.parse(localStorage.getItem('userData'));
        return userData ? userData.name : 'N/A'; // Adjust according to how you store user data
    };    

    const handleResetFilters = () => {
        setReportType('day');
        setSpecificTicket('');
        setStatus('');
        setStartDate(null);
        setEndDate(null);
        setUserId('');
        setDepartment('');
        setBuilding('');
        setCampus('');
        setNoResults(false);
    };

    return (
        <LocalizationProvider dateAdapter={AdapterLuxon}>
            <div className="flex">
                <div className="w-full">
                    <div className="w-[80%] ml-[20%] p-6">
                        <h2 className="text-2xl mb-4">Report</h2>
                        <div className="mb-6">
                            <label htmlFor="reportType" className="block text-gray-700 font-semibold mb-2">Report Type:</label>
                            <select
                                id="reportType"
                                value={reportType}
                                onChange={(e) => setReportType(e.target.value)}
                                className="w-full p-2 border border-gray-300 rounded"
                            >
                                <option value="day">Day</option>
                                <option value="week">Week</option>
                                <option value="month">Month</option>
                            </select>
                        </div>
                        <div className="mb-6">
                            <FormControl fullWidth>
                                <InputLabel>Specific Ticket</InputLabel>
                                <Select
                                    value={specificTicket}
                                    onChange={(e) => setSpecificTicket(e.target.value)}
                                >
                                    {jobOrders.map(order => (
                                        <MenuItem key={order._id} value={order._id}>
                                            {`${order.firstName} ${order.lastName} - ${order.jobDesc}`} {/* Customize as needed */}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>
                        </div>
                        <div className="mb-6">
                            <label htmlFor="status" className="block text-gray-700 font-semibold mb-2">Status:</label>
                            <select
                                id="status"
                                value={status}
                                onChange={(e) => setStatus(e.target.value)}
                                className="w-full p-2 border border-gray-300 rounded"
                            >
                                <option value="">All</option>
                                <option value="completed">Completed</option>
                                <option value="approved">Approved</option>
                                <option value="rejected">Rejected</option>
                                <option value="pending">Pending</option>
                            </select>
                        </div>
                        <div className="mb-6">
                            <label htmlFor="dateRange" className="block text-gray-700 font-semibold mb-2">Date Range:</label>
                            <div className="flex space-x-4">
                                <DesktopDatePicker
                                    label="Start Date"
                                    inputFormat="yyyy-MM-dd"
                                    value={startDate}
                                    onChange={(newDate) => setStartDate(newDate)}
                                    slots={{ textField: (params) => <TextField {...params} fullWidth /> }}
                                />
                                <DesktopDatePicker
                                    label="End Date"
                                    inputFormat="yyyy-MM-dd"
                                    value={endDate}
                                    onChange={(newDate) => setEndDate(newDate)}
                                    slots={{ textField: (params) => <TextField {...params} fullWidth /> }}
                                />
                            </div>
                        </div>
                        <div className="mb-6">
                            <label htmlFor="userId" className="block text-gray-700 font-semibold mb-2">User ID:</label>
                            <input
                                type="text"
                                id="userId"
                                value={userId}
                                onChange={(e) => setUserId(e.target.value)}
                                placeholder="Enter User ID"
                                className="w-full p-2 border border-gray-300 rounded"
                            />
                        </div>
                        <div className="mb-6">
                            <label htmlFor="department" className="block text-gray-700 font-semibold mb-2">Department:</label>
                            <input
                                type="text"
                                id="department"
                                value={department}
                                onChange={(e) => setDepartment(e.target.value)}
                                placeholder="Enter Department"
                                className="w-full p-2 border border-gray-300 rounded"
                            />
                        </div>
                        <div className="mb-6">
                            <label htmlFor="building" className="block text-gray-700 font-semibold mb-2">Building:</label>
                            <input
                                type="text"
                                id="building"
                                value={building}
                                onChange={(e) => setBuilding(e.target.value)}
                                placeholder="Enter Building"
                                className="w-full p-2 border border-gray-300 rounded"
                            />
                        </div>
                        <div className="mb-6">
                            <label htmlFor="campus" className="block text-gray-700 font-semibold mb-2">Campus:</label>
                            <input
                                type="text"
                                id="campus"
                                value={campus}
                                onChange={(e) => setCampus(e.target.value)}
                                placeholder="Enter Campus"
                                className="w-full p-2 border border-gray-300 rounded"
                            />
                        </div>
                        <div className="text-center">
                            <button
                                onClick={handleGenerateReport}
                                className="bg-gradient-to-r from-indigo-600 to-indigo-800 text-white font-semibold py-2 px-4 rounded-lg shadow-md hover:shadow-lg transition duration-150"
                            >
                                Generate Report
                            </button>
                            <button
                                onClick={handleResetFilters}
                                className="ml-4 bg-gray-300 text-black font-semibold py-2 px-4 rounded-lg shadow-md hover:shadow-lg transition duration-150"
                            >
                                Reset Filters
                            </button>
                        </div>
                        <Snackbar open={noResults} autoHideDuration={6000} onClose={() => setNoResults(false)}>
                            <Alert onClose={() => setNoResults(false)} severity="info">
                                No job orders found for the selected filters!
                            </Alert>
                        </Snackbar>
                    </div>
                </div>
            </div>
        </LocalizationProvider>
    );
};

export default CreateReport;
